language: objective-c
env:
  global:
    - LANG=en_US.UTF-8
    - LC_ALL=en_US.UTF-8
  matrix:
    - APP_TYPE=813
    - APP_TYPE=802
before_install:
  - brew update
  - if brew outdated | grep -qx xctool; then brew upgrade xctool; fi
install:
  - /bin/sh Scripts/travis-install.sh
script:
  - bundle exec rake test
after_success:
  - /bin/sh Scripts/travis-after_success.sh
notifications:
  on_success: always
  on_failure: always
  on_start: always
  webhooks:
    - 'http://ngs-hubot.herokuapp.com/travisci/hooks'

