language: objective-c
env:
  global:
    - LANG=en_US.UTF-8
    - LC_ALL=en_US.UTF-8
  matrix:
    - APP_TYPE=813
    - APP_TYPE=802
before_install:
  - brew update
  - if brew outdated | grep -qx xctool; then brew upgrade xctool; fi
install:
  - bundle install --path=vendor/bundle --binstubs=vendor/bin
  - bundle exec rake setup
script:
  - bundle exec rake test
  - bundle exec rake distribute
after_script:
  - bundle exec rake clean
notifications:
  on_success: always
  on_failure: always
  on_start: always
  webhooks:
    - 'http://ngs-hubot.herokuapp.com/travisci/hooks'

